# Site Settings
title: "Marc Sabatier Hvidkjær"
description: "Aspiring Political Scientist"
locale: "en-US"
url: "https://marchvidkjaer.com"
baseurl: ""

# Theme
theme: minima

# Markdown Processing
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author_profile: true

# Output Paths
permalink: /:title/
