baseURL = 'https://marchvidkjaer.com/'
languageCode = 'en-us'
title = 'Marc Sabatier Hvidkjaer'
publishDir = "docs"
enableGitInfo = true

[params]
description = "Marc Sabatier Hvidkjaer is a PhD candidate at Harvard University studying political representation, political behavior, and political economy."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
